main: me.kreashenz.kitpvp.KitPvP
name: Kreas-Kit
description: Kreas-Kit 2.2 The ultimate kit plugin.
version: 2.2
depend: [Vault]
# Vault is used to give the players their money rewards. 
commands:
  assassin:
    description: Choose the assassin kit.
    default: true
  kkit:
    description: Control the main Kreas-Kits abilities.
    default: true
  archer:
    description: Choose the archer kit.
    default: true
  pvp:
    description: Choose the pvp kit.
    default: true
  pyro:
    description: Choose the pyro kit.
    default: true
  tank:
    description: Choose the tank kit.
    default: true
  stats:
    description: Show your stats.
    default: true
  medic:
    description: Choose the medic kit.
    default: true
  refill:
    description: Refill your bowls
    default: true
  cupid:
    description: Choose the cupid kit.
    default: true
  knight:
    description: Choose the knight kit.
    default: true
  kitlist:
    description: Show your list of kits.